# ./bin/otelcontribcol_darwin_arm64 --config ./local/test-config.yaml
receivers:
  pulsar:
    collection_interval: 10s
    scrapers:
      network:
      memory:
exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [pulsar]
      exporters: [logging]
